src/main/java/com/example/demo/domain/Board.java
package com.example.demo.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;

import com.example.demo.dto.SearchInfo;

@Entity
@Table(name = "TEST_BOARD")
public class Board extends SearchInfo implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer idx;

	@NotNull
	@NotEmpty(message = "빈 값을 넣을 수 없습니다.")
	private String title;

	@NotNull
	@Length(max = 100)
	@NotEmpty(message = "빈 값을 넣을 수 없습니다.")
	private String contents;

	@Column(name = "REG_DATE", insertable = false)
	private Date regDate;

	@Column(name = "REG_ID")
	private String regId;

	@Column(name = "UPT_DATE")
	private Date uptDate;

	@Column(name = "UPT_ID")
	private String uptId;

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_IDX", referencedColumnName = "IDX")
	private List<BoardContents> boardContentsList;

	public Integer getIdx() {
		return idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContents() {
		return contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	public Date getRegDate() {
		return regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	public String getRegId() {
		return regId;
	}

	public void setRegId(String regId) {
		this.regId = regId;
	}

	public Date getUptDate() {
		return uptDate;
	}

	public void setUptDate(Date uptDate) {
		this.uptDate = uptDate;
	}

	public String getUptId() {
		return uptId;
	}

	public void setUptId(String uptId) {
		this.uptId = uptId;
	}

	@Override
	public String toString() {
		return "Board [idx=" + idx + ", title=" + title + ", contents=" + contents + ", regDate=" + regDate + ", regId="
				+ regId + ", uptDate=" + uptDate + ", uptId=" + uptId + "]";
	}

	public List<BoardContents> getBoardContentsList() {
		return boardContentsList;
	}

	public void setBoardContentsList(List<BoardContents> boardContentsList) {
		this.boardContentsList = boardContentsList;
	}

}

src/main/java/com/example/demo/domain/BoardContents.java
package com.example.demo.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name = "TEST_BOARD_CONTENTS")
public class BoardContents {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer idx;

	@Column(name = "FK_IDX")
	private Integer fkIdx;

	private String contents;

	@Column(name = "REG_DATE", insertable = false)
	private Date regDate;

	public Integer getIdx() {
		return idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public String getContents() {
		return contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	public Date getRegDate() {
		return regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	public Integer getFkIdx() {
		return fkIdx;
	}

	public void setFkIdx(Integer fkIdx) {
		this.fkIdx = fkIdx;
	}

}

src/main/java/com/example/demo/dto/Pagination.java
package com.example.demo.dto;

public class Pagination {

	private int itemPerPage = 20;
	private int nextPage = 10;
	private int page = 1;
	private long totalItemCount;

	public int getCurrentPage() {
		int page = this.page;
		if (page < 1) {
			page = 1;
		}
		int pageCount = getPageCount();
		if (page > pageCount) {
			page = pageCount;
		}
		return page;
	}

	public int getPageCount() {
		return (int) ((totalItemCount - 1) / itemPerPage + 1);
	}

	public int getPageBegin() {
		return ((getCurrentPage() - 1) / nextPage) * nextPage + 1;
	}

	public int getPageEnd() {
		int pageCount = getPageCount();
		int num = getPageBegin() + nextPage - 1;
		return Math.min(pageCount, num);
	}

	public long getTotalItemCount() {
		return totalItemCount;
	}

	public void setTotalItemCount(long totalItemCount) {
		this.totalItemCount = totalItemCount;
	}

	public int getItemPerPage() {
		return itemPerPage;
	}

	public void setItemPerPage(int itemPerPage) {
		this.itemPerPage = itemPerPage;
	}

	public int getNextPage() {
		return nextPage;
	}

	public void setNextPage(int nextPage) {
		this.nextPage = nextPage;
	}

	public int getPage() {
		return page;
	}

	public void setPage(int page) {
		this.page = page;
	}

	public int getCurrentItem() {
		return (page - 1) * itemPerPage;
	}
	
	public int getCurrentItemEnd(){
		return page * itemPerPage;
	}

	public int getJumpNextPage() {
		return Math.min(getPageCount(), page + nextPage);
	}

	public int getJumpPrevPage() {
		return Math.max(1, page - nextPage);
	}
	
	public int getLastPage(){
		return (int) Math.ceil(1.0*getTotalItemCount()/itemPerPage);
	}

	@Override
	public String toString() {
		return page > 1 ? "page : "+ page : "";   
	}

}

src/main/java/com/example/demo/dto/SearchInfo.java
package com.example.demo.dto;

public class SearchInfo extends Pagination{

	private String searchOption;
	private String searchInput;
	private boolean isSearch = false;

	public String getSearchOption() {
		return searchOption;
	}

	public void setSearchOption(String searchOption) {
		this.searchOption = searchOption;
	}

	public String getSearchInput() {
		return searchInput;
	}

	public void setSearchInput(String searchInput) {
		this.searchInput = searchInput;
	}

	public boolean isSearch() {
		return isSearch;
	}

	public void setSearch(boolean isSearch) {
		this.isSearch = isSearch;
	}

}

src/main/java/com/example/demo/web/BoardController.java
package com.example.demo.web;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import com.example.demo.domain.Board;
import com.example.demo.service.BoardService;

@Controller
@RequestMapping(value = "/board")
public class BoardController {

	@Autowired private BoardService boardService;
	
	@GetMapping(value = "/list")
	public void list(Model model, Board board ) {
		board.setItemPerPage(10);
		Page<Board> list = boardService.findAll(board);
		model.addAttribute("list", list);
		model.addAttribute("pagination", board);
	}
	
	@GetMapping(value = "/register")
	public void register() {
	}
	
	@PostMapping(value = "/register-proc")
	public String registerProc(Board board) {
		board.setRegId("test");
		try {
			boardService.save(board);
		} catch (Exception e) {
			e.printStackTrace();
			//redirect error page?
		}
		return "redirect:list";
	}
	
	@GetMapping(value = "/modify")
	public void modify(Model model, Board board) {
		model.addAttribute("item", boardService.findByIdx(board));
	}
	
	@GetMapping(value = "/view")
	public void view(Model model, Board board) {
		model.addAttribute("item", boardService.findByIdx(board));
	}
	
}

src/main/java/com/example/demo/web/MainController.java
package com.example.demo.web;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
public class MainController {

	@RequestMapping(value = "/index")
	public String index(Model model) {
		return "index";
	}
	
}

src/main/webapp/WEB-INF/views/board/list.jsp
<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<%@ include file="../include/top.jsp"%>
<%@ include file="../include/menu.jsp"%>	
	<main role="main" class="flex-shrink-0">
		<div class="container">
			<form method="get" >
				<div class="input-group mt-3 mb-3">
					<select name="searchOption" class="input-group-append custom-select col-sm-2">
						<option value="">전체</option>
						<option value="name">작성자</option>
						<option value="title">제목</option>
						<option value="contents">내용</option>
					</select>
					<input type="text" name="searchInput" class="form-control col-sm-3" placeholder="Search ..." aria-describedby="button-addon2" value="${board.searchInput }">
					<div class="input-group-append"><button class="btn btn-outline-secondary" type="button" id="button-addon2" onclick="searchList();">Button</button></div>
				</div>
				<table class="table table-striped">
					<thead>
						<tr>
							<th scope="col">#</th>
							<th scope="col">Title</th>
							<th scope="col">REG_DATE</th>
							<th scope="col">REG_ID</th>
						</tr>
					</thead>
					<tbody>
						<c:forEach items="${list.content }" var="vList" varStatus="count">
							<tr>
								<th scope="row">${list.totalElements - (pagination.page - 1) * pagination.itemPerPage - count.count + 1 }</th>
								<td><a href="view?idx=${vList[0].idx}">${vList[0].title }</a> (${vList[1]})</td>
								<td><fmt:formatDate pattern="yyyy-MM-dd" value="${vList[0].regDate }"/> </td>
								<td>${vList[0].regId }</td>
							</tr>
						</c:forEach>
					</tbody>
				</table>
				<div class="float-right">
					<a href="register" class="btn btn-primary">등록</a>
				</div>	
				<%@ include file="../include/pagination.jsp"%>
			</form>			
		</div>
	</main>
	<%@ include file="../include/js.jsp"%>
	<script>
	function searchList(){
		$('#page').val(1);
		$('.container form').submit();
	}
	$('select[name="searchOption"]').val('${board.searchOption}');
	</script>
<%@ include file="../include/footer.jsp"%>

src/main/webapp/WEB-INF/views/board/register.jsp
<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<%@ include file="../include/top.jsp"%>
<%@ include file="../include/menu.jsp"%>	
	<main role="main" class="flex-shrink-0">
		<div class="container">
			<form method="post" >
				<div class="row">
				    <div class="col-md-8 order-md-1">
				      <h4 class="mb-3">Register</h4>
			          <div class="mb-3">
			            <label for="title">Title</label>
			            <input type="text" class="form-control" id="title" name="title" placeholder="" value="" required>
			          </div>
			          <div class="mb-3">
			            <label for="contents">Contents</label>
			            <textarea class="form-control" id="contents" name="contents" rows="8" cols="10" required></textarea>
			          </div>
				        <hr class="mb-4">
				        <h4 class="mb-3">Option</h4>
				         <div class="row mb-2">
				        	<div class="col-md-11"><input type="text" class="form-control" name="boardContentsList[0].contents" placeholder="" value=""></div><div class="col-md-1"><button class="btn btn-primary" type="button">+</button></div>
				        </div>
				        <div class="row mb-2">
				        	<div class="col-md-11"><input type="text" class="form-control" name="boardContentsList[1].contents" placeholder="" value=""></div><div class="col-md-1"><button class="btn btn-primary" type="button"> - </button></div>
				        </div>
				        <div class="row mb-2">
				        	<div class="col-md-11"><input type="text" class="form-control" name="boardContentsList[2].contents" placeholder="" value=""></div><div class="col-md-1"><button class="btn btn-primary" type="button"> - </button></div>
				        </div>
				        <hr class="mb-4">
				        <button class="btn btn-primary btn-lg btn-block" type="button" onclick="regForm();">등록</button>
				    </div>
				  </div>	
			</form>			
		</div>
	</main>
	<%@ include file="../include/js.jsp"%>
	<script>
	var regForm = function(){
		if(!confirm('등록하시겠습니까?')) return;
		
		$('.container form').attr('action', 'register-proc').submit();
	}
		
	</script>
<%@ include file="../include/footer.jsp"%>

src/main/webapp/WEB-INF/views/board/view.jsp
<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<%@ include file="../include/top.jsp"%>
<%@ include file="../include/menu.jsp"%>	
	<main role="main" class="flex-shrink-0">
		<div class="container">
			<form method="post" >
				<div class="row">
				    <div class="col-md-8 order-md-1">
				      <h4 class="mb-3">View</h4>
			          <div class="mb-3">
			            <label for="title">Title</label>
			            <input type="text" class="form-control" id="title" name="title" placeholder="" readonly="readonly" value="${item.title }" required>
			          </div>
			          <div class="mb-3">
			            <label for="contents">Contents</label>
			            <textarea class="form-control" id="contents" name="contents" rows="8" cols="10" readonly="readonly" required>${item.contents }</textarea>
			          </div>
				        <hr class="mb-4">
				        <h4 class="mb-3">Option</h4>
				        <c:forEach items="${item.boardContentsList }" var="list">
				        	<div class="row mb-2">
					        	<div class="col-md-12"><input type="text" class="form-control"  placeholder="" readonly="readonly" value="${list.contents }"></div>
					        </div>
				        </c:forEach>
				        <hr class="mb-4">
				    </div>
				  </div>	
			</form>			
		</div>
	</main>
	<%@ include file="../include/js.jsp"%>
	<script>
	</script>
<%@ include file="../include/footer.jsp"%>

src/main/webapp/WEB-INF/views/include/footer.jsp
<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>
</body>
</html>

src/main/webapp/WEB-INF/views/include/js.jsp
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

src/main/webapp/WEB-INF/views/include/menu.jsp
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
	<a class="navbar-brand" href="#">Fixed navbar</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarCollapse">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item active"><a class="nav-link" href="#">Home
					<span class="sr-only">(current)</span>
			</a></li>
			<li class="nav-item"><a class="nav-link" href="#">Link</a></li>
			<li class="nav-item"><a class="nav-link disabled" href="#"
				tabindex="-1" aria-disabled="true">Disabled</a></li>
		</ul>
	</div>
</nav>

src/main/webapp/WEB-INF/views/include/pagination.jsp
<script type="text/javascript">
	function goPage(page){
		$("#page").val(page);
		$(".container form").submit();
	};
</script>
<input type="hidden" name="search" value="true" />
<input type="hidden" id="page" name="page" value="${pagination.page}" />
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    <li class="page-item"><a class="page-link" href="#" onclick="goPage('${pagination.jumpPrevPage}')"><</a></li>
    <c:forEach begin="${pagination.pageBegin }" end="${pagination.pageEnd }" step="1" var="pageNumber">
		<c:choose>
			<c:when test="${pagination.currentPage == pageNumber }">
				<li class="page-item active"><a class="page-link" href="#">${pageNumber }</a></li>
			</c:when>
			<c:otherwise>
				<li class="page-item"><a class="page-link" href="#" onclick="goPage('${pageNumber }')">${pageNumber }</a></li>
			</c:otherwise>
		</c:choose>
	</c:forEach>
    <li class="page-item"><a class="page-link" href="#" onclick="goPage('${pagination.jumpNextPage }')">></a></li>
  </ul>
</nav>	

src/main/webapp/WEB-INF/views/include/top.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<!DOCTYPE html>
<html class="h-100"> 
<head>
<title>Insert title here</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="/resources/css/common.css">
</head>
<body class="d-flex flex-column h-100">

src/main/webapp/WEB-INF/views/index.jsp
<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<%@ include file="include/top.jsp"%>
<%@ include file="include/menu.jsp"%>	
	<main role="main" class="flex-shrink-0">
		<div class="container">
			<c:forEach items="${list }" var="list">
				${list }
			</c:forEach>	
		</div>
	</main>
<%@ include file="include/footer.jsp"%>